schema_version: "1.0"
id: medieval_mod_reborn
display_name: Medieval Mod Reborn
short_description: >-
  The official replacement for and expansion of the Medieval and Historic
  Content mod, Bright Nights version.
description: >-
  The official replacement for and expansion of the Medieval and Historic
  Content mod, Bright Nights version.
author:
  - Chaosvolt
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/chaosvolt/cdda_medieval_mod_reborn/tree/master/Medieval_Mod_Reborn_BN
version: 2026.10.9-364a66e
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: bc8a31d64dc5a19b7e45f67d8cbbf41cee315d8d
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-05-16T09:24:08.238Z"
  - version: 2026.6.8-bc8a31d
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: bc8a31d64dc5a19b7e45f67d8cbbf41cee315d8d
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-06-08T03:02:49.348Z"
  - version: 2026.6.9-bc8a31d
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: bc8a31d64dc5a19b7e45f67d8cbbf41cee315d8d
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-06-09T02:39:40.142Z"
  - version: 2026.6.10-bc8a31d
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: bc8a31d64dc5a19b7e45f67d8cbbf41cee315d8d
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-06-10T02:55:43.861Z"
  - version: 2026.6.11-bc8a31d
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: bc8a31d64dc5a19b7e45f67d8cbbf41cee315d8d
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-06-11T02:58:18.842Z"
  - version: 2026.6.12-bc8a31d
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: bc8a31d64dc5a19b7e45f67d8cbbf41cee315d8d
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-06-12T03:01:31.298Z"
  - version: 2026.6.13-bc8a31d
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: bc8a31d64dc5a19b7e45f67d8cbbf41cee315d8d
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-06-13T02:48:50.800Z"
  - version: 2026.6.14-bc8a31d
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: bc8a31d64dc5a19b7e45f67d8cbbf41cee315d8d
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-06-14T02:59:08.590Z"
  - version: 2026.6.15-bc8a31d
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: bc8a31d64dc5a19b7e45f67d8cbbf41cee315d8d
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-06-15T03:32:38.890Z"
  - version: 2026.6.16-bc8a31d
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: bc8a31d64dc5a19b7e45f67d8cbbf41cee315d8d
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-06-16T03:34:34.520Z"
  - version: 2026.6.17-859c295
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: 859c295dccf3ff2c2f78343a4a328ad211b6d158
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-06-17T03:26:36.953Z"
  - version: 2026.6.18-859c295
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: 859c295dccf3ff2c2f78343a4a328ad211b6d158
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-06-18T03:01:26.657Z"
  - version: 2026.6.19-859c295
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: 859c295dccf3ff2c2f78343a4a328ad211b6d158
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-06-19T03:55:54.075Z"
  - version: 2026.6.20-859c295
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: 859c295dccf3ff2c2f78343a4a328ad211b6d158
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-06-20T02:48:53.752Z"
  - version: 2026.8.2-1b270e8
    source:
      type: github_archive
      url: >-
        https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
      commit_sha: 1b270e80127c23f8905c6ff4d980cb7f182f5ffe
      extract_path: Medieval_Mod_Reborn_BN
    released_at: "2026-08-02T02:07:29.823Z"
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: >-
    https://github.com/chaosvolt/cdda_medieval_mod_reborn/archive/refs/heads/master.zip
  commit_sha: 364a66e93a52a3eb2e0edd09cccb936f80e16f2b
  extract_path: Medieval_Mod_Reborn_BN
categories:
  - items
modinfo_url: >-
  https://raw.githubusercontent.com/chaosvolt/cdda_medieval_mod_reborn/bc8a31d64dc5a19b7e45f67d8cbbf41cee315d8d/Medieval_Mod_Reborn_BN/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: master
last_updated: "2026-10-09T04:03:55.551Z"
