schema_version: "1.0"
id: realdarkskies_arcana_plus_patchmod
display_name: Really Dark Skies plus Arcana's patchmods
short_description: >-
  A patchmod for Really Dark Skies which adds increased support for Arcana, and
  its numerous patchmods
description: >-
  A patchmod for Really Dark Skies which adds increased support for Arcana, and
  its numerous patchmods
author:
  - Zlorthishen
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/Really_Dark_Skies/tree/main/Patch_mods/RDS_plus_Arcana_plus
version: 2026.6.20-4e6abff
previous_releases:
  - version: 0.0.0
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Arcana_plus
    released_at: "2026-05-16T09:24:59.311Z"
  - version: 2026.6.8-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Arcana_plus
    released_at: "2026-06-08T03:02:48.692Z"
  - version: 2026.6.9-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Arcana_plus
    released_at: "2026-06-09T02:39:39.392Z"
  - version: 2026.6.10-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Arcana_plus
    released_at: "2026-06-10T02:55:55.835Z"
  - version: 2026.6.11-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Arcana_plus
    released_at: "2026-06-11T02:58:50.222Z"
  - version: 2026.6.12-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Arcana_plus
    released_at: "2026-06-12T03:01:48.077Z"
  - version: 2026.6.13-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Arcana_plus
    released_at: "2026-06-13T02:49:06.838Z"
  - version: 2026.6.14-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Arcana_plus
    released_at: "2026-06-14T02:59:36.996Z"
  - version: 2026.6.15-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Arcana_plus
    released_at: "2026-06-15T03:32:50.657Z"
  - version: 2026.6.16-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Arcana_plus
    released_at: "2026-06-16T03:34:51.193Z"
  - version: 2026.6.17-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Arcana_plus
    released_at: "2026-06-17T03:26:49.432Z"
  - version: 2026.6.18-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Arcana_plus
    released_at: "2026-06-18T03:01:52.516Z"
  - version: 2026.6.19-4e6abff
    source:
      type: github_archive
      url: >-
        https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip
      commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
      extract_path: Patch_mods/RDS_plus_Arcana_plus
    released_at: "2026-06-19T03:56:19.653Z"
yanked:
  reason: "Requires removed Arcana patchmods that were replaced by mod_interactions."
dependencies:
  bn: ">=0.9.1"
  realdarkskies: "*"
  arcana_dinomod_patch: "*"
  arcana_cata++_patch: "*"
  arcana_crit_patch: "*"
  arcana_magiclalnights_patch: "*"
  arcana_aftershock_patch: "*"
source:
  type: github_archive
  url: "https://github.com/Zlorthishen/Really_Dark_Skies/archive/refs/heads/main.zip"
  commit_sha: 4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea
  extract_path: Patch_mods/RDS_plus_Arcana_plus
categories:
  - misc_additions
modinfo_url: >-
  https://raw.githubusercontent.com/Zlorthishen/Really_Dark_Skies/4e6abff37d33cfaac6cc43ff1eedcdf5abea17ea/Patch_mods/RDS_plus_Arcana_plus/modinfo.json
uses_lua: false
autoupdate:
  type: commit
  branch: main
parent: realdarkskies
last_updated: "2026-06-20T02:49:09.125Z"
